Bshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls'))
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store.views.store import home,Index1
from store.views.login import Login,logout
from store.views.signup import Signup
from store.views.cart import Cart
from store.views.orders import OrderView
from store.views.checkout import checkout
from store.views.admin_order import admin_orders
from store.views.admin_product import admin_product,product_edit,product_delete,product_add
app_name='store'
urlpatterns = [
    path('', Index1.as_view(), name='homepage'),
    path('home/',home.as_view(),name='home'),
    path('login/',Login.as_view(),name='login'),
    path('signup/',Signup.as_view(),name='signup'),
    path('logout/',logout,name='logout'),
    path('check-out', checkout.as_view() , name='checkout'),
    path('cart/',Cart.as_view(),name='cart'),
    path('orders', (OrderView.as_view()), name='orders'),
    path('manage_order/', (admin_orders.as_view()), name='manage'),
    path('manage_product/', (admin_product.as_view()), name='manage1'),
    path('product_edit/',product_edit.as_view(),name='order_edit'),
    path('product_add/',product_add.as_view(),name='product_add'),
    path('product_delete/',product_delete,name='product_add')
]

store/models/Category.py
from django.db import models

class Category(models.Model):
    name=models.CharField(max_length=20)
    def __str__(self):
        return self.name

store/models/Customer.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    first_name = models.CharField(max_length=50,null=True, blank=True)
    last_name = models.CharField(max_length=50,null=True, blank=True)
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    isadmin=models.BooleanField(null=False)
    password = models.CharField(max_length=500)
    def register(self):
        self.save()

    def __str__(self):
        return self.email

    def isExists(self):

        if Customer.objects.filter(email = self.email):
            return True

        return  False

store/models/Order.py
from django.db import models
from store.models.Products import Product
from store.models.Customer import Customer
import datetime


class Order(models.Model):
    product = models.ForeignKey(Product,
                                on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer,
                                 on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.IntegerField()
    address = models.CharField(max_length=50, default='', blank=True)
    phone = models.CharField(max_length=50, default='', blank=True)
    date = models.DateField(default=datetime.datetime.today)
    status = models.BooleanField(default=False)

    def placeOrder(self):
        self.save()
    def __str__(self):
        return self.phone
    @staticmethod
    def get_orders_by_customer(customer_id):
        return Order.objects.filter(customer=customer_id).order_by('-date')

store/models/OrderItem.py
from django.db import models

store/models/Products.py
from django.db import models
from store.models.Category import Category
class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.FloatField()
    digital = models.BooleanField(default=False, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    category=models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    instock=models.IntegerField(null=True)
    def __str__(self):
        return self.name

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url

store/models/ShippingAddress.py
from django.db import models

store/views/admin_order.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render , redirect , HttpResponseRedirect

from django.contrib.auth.hashers import  check_password
from store.models.Customer import Customer
from store.models.Products import Product
from store.models.Order import Order
from django.views import  View
from django.core.paginator import Paginator
class admin_orders(View):

    def get(self,request):
        m = request.session.get('customer')

        if Customer.objects.filter(id=m):
            print('co pha la admin', )
            customer = Customer.objects.get(id=m)
            if customer.isadmin :
                array = []
                orders = Order.objects.filter(status=False).order_by('date')
                orders1 = Order.objects.filter(status=True).order_by('date')
                for i in orders:
                    array.append(i)
                for i in orders1:
                    array.append(i)
                paginator = Paginator(array, 2)
                print(array)
                page_number = request.GET.get('page')
                page_obj = paginator.get_page(page_number)
                return render(request, 'store/admin_orders.html', {'page': page_obj})
            else:
                return redirect('store:home')
        else:
            return redirect('store:home')
    def post(self,request):
        status=request.POST.get('status')
        product = request.POST.get('productid')
        customer = request.POST.get('customer')
        print('hello')
        print(status)
        print(product)
        print(customer)
        print('-------------------')
        customer_order=Customer.objects.get(email=customer)
        product_id=Product.objects.get(name=product)
        order=Order.objects.filter(customer=customer_order,product=product_id).update(status=True)
        print(customer_order.id)



        return redirect('store:manage')

store/views/admin_product.py
from django.shortcuts import render , redirect , HttpResponseRedirect

from django.contrib.auth.hashers import  check_password
from store.models.Customer import Customer
from store.models.Products import Product
from store.models.Category import Category
from django.views import  View
from django.core.paginator import Paginator
class admin_product(View):
    def get(self,request):
        m = request.session.get('customer')
        if Customer.objects.filter(id=m):
            customer = Customer.objects.get(id=m)
            if customer.isadmin :
                product=Product.objects.all()
                paginator = Paginator(product, 5)
                print(product)
                page_number = request.GET.get('page')
                page_obj = paginator.get_page(page_number)
                category=Category.objects.all()
                print(category)
                return render(request,'store/asd.html',{'page' : page_obj,'category':category})
            else:
                return redirect('store:home')
        else:
            return redirect('store:home')
class product_edit(View):
    def get(self,request):
        name=request.GET.get('name1')
        print('sadsafb!!!',name)
        product=Product.objects.get(name=name)
        category = Category.objects.exclude(name=product.category)
        return render(request,'store/admin_product_edit.html',{'product':product,'category':category})
    def post(self,request):
        name = request.POST.get('name')
        name1 = request.POST.get('asd')
        print(name,'sd',name1)
        product=Product.objects.get(name=name1)
        print(product,'sds')
        category1 = request.POST.get('category')
        stock = request.POST.get('stock')
        image = request.POST.get('fileInput')
        price = request.POST.get('Price')
        print((category1, price,stock, image, name))
        cate=Category.objects.get(name=category1)
        if image:
            product.image=image
        else:
            image=product.image
        product.name=name
        product.instock=stock
        product.image=image
        product.price=price
        product.category.id=cate.id
        product.save()
        print('name moi',)
        return  redirect('store:home')
class product_add(View):
    def get(self,request):
        m = request.session.get('customer')
        if Customer.objects.filter(id=m):
            customer = Customer.objects.get(id=m)
            if customer.isadmin:
                category=Category.objects.all()
                return  render(request,'store/admin_product_add.html',{'category':category})
            else:
                return redirect('store:home')
        return  redirect('store:home')
    def post(self,request):
        name = request.POST.get('name')
        category1 = request.POST.get('category')
        stock = request.POST.get('stock')
        image = request.POST.get('fileInput')
        price = request.POST.get('Price')
        print((category1, price,stock, image, name))
        cate=Category.objects.get(name=category1)

        product=Product(name=name,instock=stock,image=image,price=price,category=Category(id=cate.id))
        product.save()
        return  redirect('store:home')
def product_delete(request):
    message="Xoa Thanh Cong"
    name = request.GET.get('name')
    print('ten la ',name)
    product = Product.objects.get(name=name)
    product.delete()
    return redirect('store:manage1')

store/views/cart.py
from django.shortcuts import render , redirect , HttpResponseRedirect

from django.contrib.auth.hashers import  check_password
from store.models.Customer import Customer
from store.models.Products import Product
from django.views import  View
from django.contrib.auth.decorators import login_required

class Cart(View):

    def get(self, request):
        if request.session.get('customer'):
            ids = list(request.session.get('cart').keys())
            print('ids',ids)
            products = Product.objects.filter(id__in =ids)
            print(products)
            return render(request, 'store/cart.html', {'products': products})
        else:
            return redirect('store:login')

store/views/checkout.py
from django.shortcuts import render, redirect

from django.contrib.auth.hashers import check_password
from store.models.Customer import Customer
from django.views import View

from store.models.Products import Product
from store.models.Order import Order


class checkout(View):
    def post(self, request):
        address = request.POST.get('address')
        phone = request.POST.get('phone')
        customer = request.session.get('customer')
        cart = request.session.get('cart')
        products = Product.objects.filter(id__in =list(cart.keys()))
        print(address, phone, customer, cart, products)
        customerId=Customer.objects.get(id=customer)
        for product in products:
            print(cart.get(str(product.id)))
            order = Order(customer=Customer(id=customer),
                          product=product,
                          price=product.price,
                          address=address,
                          phone=phone,
                          quantity=cart.get(str(product.id)))
            order.save()
            product.instock=product.instock-cart.get(str(product.id))
            product.save()
            print(product.instock)
        request.session['cart'] = {}

        return redirect('store:cart')

store/views/login.py
from django.shortcuts import render , redirect , HttpResponseRedirect
from django.contrib.auth import authenticate
from django.contrib.auth.hashers import  check_password,get_hasher
from store.models.Customer import Customer
from store.models.Products import Product
from django.views import  View


class Login(View):
    return_url = None
    def get(self , request):
        print('asasa')
        Login.return_url = request.GET.get('return_url')
        return render(request , 'store/login.html')

    def post(self , request):
        email1 = request.POST.get('email')
        print(email1)
        password = request.POST.get('password')
        print(password)
        customer=Customer.objects.filter(email=email1)

        error_message = None

        if customer:
            customer1=Customer.objects.get(email=email1)
            print(customer1.password)
            flag=check_password(password,customer1.password)
            print(flag)
            if flag:
                print('ok')
                request.session['customer'] = customer1.id
                request.session['customer_isadmin']=customer1.isadmin
                return redirect('store:home')
            else:
                print('1')
                error_message='Email or Password invalid !!'
        else:
            error_message = 'Email or Password invalid !!'

        print(email1, password)
        return render(request, 'store/login.html', {'error': error_message})

def logout(request):
    request.session.clear()
    return redirect('store:home')

store/views/orders.py
from django.shortcuts import render, redirect

from django.contrib.auth.hashers import check_password
from store.models.Customer import Customer
from django.views import View

from store.models.Products import Product
from store.models.Order import Order
from store.middlewares.auth import auth_middleware

class OrderView(View):
    def get(self , request ):
        if request.session.get('customer'):
            customer = request.session.get('customer')
            orders = Order.get_orders_by_customer(customer)
            print(orders)
            print(orders)
            return render(request , 'store/orders.html'  , {'orders' : orders})
        else:
            return redirect('store:login')

store/views/signup.py
from django.shortcuts import render, redirect
from django.contrib.auth.hashers import make_password
from store.models.Customer import Customer
from django.views import View
from django.core.mail import send_mail

class Signup(View):
    def get(self, request):
        return render(request, 'store/signup.html')

    def post(self, request):
        postData = request.POST
        first_name = postData.get('firstname')
        last_name = postData.get('lastname')
        phone = postData.get('phone')
        email = postData.get('email')
        password = postData.get('password')
        # validation
        value = {
            'first_name': first_name,
            'last_name': last_name,
            'phone': phone,
            'email': email
        }
        error_message = None

        customer = Customer(first_name=first_name,
                            last_name=last_name,
                            phone=phone,
                            email=email,
                            isadmin=False,
                            password=password)
        error_message = self.validateCustomer(customer)
        data = """
                Hello! I am Phuc.
            """
        send_mail('Welcome!', data, "nghiats188 @gmail.com", [email], fail_silently=False)
        if not error_message:
            print(first_name, last_name, phone, email, password)
            customer.password = make_password(customer.password)
            customer.save()
            request.session['customer'] = customer.id
            return redirect('store:home')
        else:
            data = {
                'error': error_message,
                'values': value
            }
            return render(request, 'store/signup.html', data)


    def validateCustomer(self, customer):
        error_message = None;
        if (not customer.first_name):
            error_message = "First Name Required !!"
        elif len(customer.first_name) < 4:
            error_message = 'First Name must be 4 char long or more'
        elif not customer.last_name:
            error_message = 'Last Name Required'
        elif len(customer.last_name) < 4:
            error_message = 'Last Name must be 4 char long or more'
        elif not customer.phone:
            error_message = 'Phone Number required'
        elif len(customer.phone) < 10:
            error_message = 'Phone Number must be 10 char Long'
        elif len(customer.password) < 6:
            error_message = 'Password must be 6 char long'
        elif len(customer.email) < 5:
            error_message = 'Email must be 5 char long'
        elif self.customerisexists(customer):
            error_message = 'Email Address Already Registered..'
        # saving
        return error_message
    def customerisexists(self,customer):
        if Customer.objects.filter(email=customer.email):
            return True
        return False

store/templates/store/admin_orders.html
{% extends 'store/base.html' %}
{% load static%}

{% block content %}
{% load cart %}
{% load custom_filter %}
<div class="container">
   <div class="border rounded p-4 m-4">
        <p class="display-4 pl-4 ml-4">Your Orders</p>
        <hr>
        <table class="table">
            <thead>
                <tr>
                    <th>Sno.</th>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Date</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Total</th>
                    <th>Status</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                
                {% for order in page %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td><img style="height: 80px;" class="rounded-circle" src="{{order.product.image.url}}" alt=""></td>
                    <td >{{order.product.name}}</td>
                    <td>{{order.date}}</td>
                    <td>{{order.price|currency}}</td>
                    <td>{{order.quantity}}</td>
                    <td>{{order.quantity|multiply:order.price|currency}}</td>
                    {% if order.status %}
                    <td><small class="badge badge-success">Completed</small></td>
                    {%else%}
                    <td><small class="badge badge-warning">Pending</small></td>
                    {% endif %}

                    <form action="/manage_order/" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="status" value="{{ order.status }}">
                    <input type="hidden" name="customer" value="{{ order.customer }}">
                    <input type="hidden" name="productid" value="{{ order.product }}">
                    {% if order.status %}
                    <td><input class="btn btn-sm btn-info col-lg-8" type="button"  value="submit" style="background:#90EE90;color:black"  %}
                        <li class="disabled"></td>
                    {% else %}
                    <td><input class="btn btn-sm btn-info col-lg-8" type="submit" value="submit" style="background:#F0E68C;color:black" value="submit"></td>
                     {% endif %}
                    </form>
                </tr>

                {% endfor %}

            </tbody>

        </table>
       
   </div>
   <nav class="mt-4 container1" aria-label="Page navigation sample" style=" margin: auto">
					<ul class="pagination">
						{% if page.has_previous %}
						<li class="page-item">
							<a class="page-link" href="{% url 'store:manage' %}?page=1">First</a>
						</li>
						<li class="page-item">
							<a class="page-link"
								href="{% url 'store:manage' %}?page={{page.previous_page_number}}">Previous</a>
						</li>
                        {% else %}
						<li class="page-item disabled">
							<a class="page-link" href="#">First</a>
						</li>
						<li class="page-item disabled">
							<a class="page-link" href="#">Previous</a>
						</li>
						{% endif %}

						{% for i in page.paginator.page_range %}

						{% if i == page.number %}
						<li class="page-item active">
							<a class="page-link" href="{% url 'store:manage' %}?page={{ i }}">{{ i }}</a>
						</li>
						{% else %}
						<li class="page-item">
							<a class="page-link" href="{% url 'store:manage' %}?page={{ i }}">{{ i }}</a>
						</li>
						{% endif %}

						{% endfor %}

						{% if page.has_next %}
                        <li class="page-item">
							<a class="page-link" href="{% url 'store:manage' %}?page={{page.next_page_number}}">Next</a>
						</li>
						<li class="page-item">
							<a class="page-link"
								href="{% url 'store:manage' %}?page={{ page.paginator.num_pages }}">Last</a>
						</li>
						{% else %}
						<li class="page-item disabled">
							<a class="page-link" href="#">Next</a>
						</li>
						<li class="page-item disabled">
							<a class="page-link" href="#">Last</a>
						</li>
                        {% endif %}
					</ul>
   </nav>


</div>

<style>
    .container1 {
  width: 500px;
  margin: auto;
  text-align: center;
}
.pagination {
  width: 400px;
  margin-left: 50px;
}
.pagination a {
  display: block;
  color: black;
  float: left;
  padding: 8px 16px;
  text-decoration: none;
  transition: background-color .3s;
}

.pagination a.active {
    background-color: #4CAF50;
    color: white;
}

.pagination a:hover:not(.active) {
  background-color: #ddd;
}
</style>



{% endblock %}

store/templates/store/admin_product_add.html
{% extends 'store/base.html' %}
{% load static%}

{% block content %}
{% load cart %}
{% load custom_filter %}
<div class="container">
  <div class="border rounded p-4 m-4">
    <div class="container tm-mt-big tm-mb-big">
      <div class="row">
        <div class="col-xl-9 col-lg-10 col-md-12 col-sm-12 mx-auto">
          <div class="tm-bg-primary-dark tm-block tm-block-h-auto">
            <div class="row">
              <div class="col-12">
                <h2 class="tm-block-title d-inline-block">Add Product</h2>
              </div>
            </div>
            <div class="row tm-edit-product-row">
              <div class="col-xl-6 col-lg-6 col-md-12">
                <form action="/product_add/" method="post" class="tm-edit-product-form">
                   {% csrf_token %}
                  <div class="form-group mb-3">
                    <label
                      for="name"
                      >Product Name
                    </label>
                    <input
                      id="name"
                      name="name"
                      type="text"
                      class="form-control validate"
                      required
                    />
                  </div>
                  <div class="form-group mb-3">

                  </div>
                  <div class="form-group mb-3">
                    <label
                      for="category"
                      >Category</label
                    >
                    <select
                      class="custom-select tm-select-accounts"
                      id="category" name="category"
                    >
                      <option selected>Select category</option>
                      {% for i in category %}
                      <option value="{{i.name}}">{{i.name}}</option>
                      {% endfor %}
                    </select>
                  </div>
                  <div class="row">
                        <div class="form-group mb-3 col-xs-12 col-sm-6">
                          <label
                            for="Price"
                            >Price
                          </label>
                          <input
                            id="Price"
                            name="Price"
                            type="text"
                            class="form-control validate"
                            required
                          />
                        </div>
                        <div class="form-group mb-3 col-xs-12 col-sm-6">
                          <label
                            for="stock"
                            >Units In Stock
                          </label>
                          <input
                            id="stock"
                            name="stock"
                            type="text"
                            class="form-control validate"
                            required
                          />
                        </div>
                  </div>

              </div>
              <div class="col-xl-6 col-lg-6 col-md-12 mx-auto mb-4">

                <div class="custom-file mt-3 mb-3">
                  <img id="image" style="height:200px;width:200px;margin:10px"/>
                  <input id="fileInput" type="file" name="fileInput" style="display:none;" />
                  <input
                    type="button"
                    class="btn btn-primary btn-block mx-auto"
                    value="UPLOAD PRODUCT IMAGE"
                    onclick="document.getElementById('fileInput').click();"
                  />
                </div>
              </div>
              <div class="col-12">
                <button type="submit" class="btn btn-primary btn-block text-uppercase">Add Product Now</button>
              </div>
            </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
document.getElementById("fileInput").onchange = function () {
    var reader = new FileReader();

    reader.onload = function (e) {
        // get loaded data and render thumbnail.
        document.getElementById("image").src = e.target.result;
    };

    // read the image file as a data URL.
    reader.readAsDataURL(this.files[0]);
};
</script>
<head>
<script  src = "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js" ></script >
</head>
{% endblock %}
<tdsa><img style="height: 80px;" class="rounded-circle" src="{{order.image.url}}" alt=""></tdsa>

store/templates/store/base.html
<!doctype html>
<html lang="en">
{% load static%}
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'pagi.css' %}">
  <title>Hello, world!</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
<script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Product Page - Admin HTML Template</title>
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Roboto:400,700"
    />

    <!--
	Product Admin CSS Template
	https://templatemo.com/tm-524-product-admin
	-->
  <style>
    .modal-5 {
  position: relative;
}
.modal-5:after {
  content: ';
  position: absolute;
  awidth: 100%;
  height: 35px;
  left: 0;
  bottom: 0;
  z-index: -1;
  background-image: -moz-linear-gradient(left, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.65) 40%, rgba(0, 0, 0, 0.65) 50%, rgba(0, 0, 0, 0.65) 60%, rgba(0, 0, 0, 0) 100%);
  background-image: -webkit-linear-gradient(left, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.65) 40%, rgba(0, 0, 0, 0.65) 50%, rgba(0, 0, 0, 0.65) 60%, rgba(0, 0, 0, 0) 100%);
  background-image: linear-gradient(to right, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.65) 40%, rgba(0, 0, 0, 0.65) 50%, rgba(0, 0, 0, 0.65) 60%, rgba(0, 0, 0, 0) 100%);
}
.modal-5 a {
  color: #666;
  padding: 13px 5px 5px;
  margin: 0 10px;
  position: relative;
}
.modal-5 a:hover {
  color: #fff;
}
.modal-5 a:hover:after {
  content: ';
  position: absolute;
  awidth: 24px;
  height: 24px;
  background: #1E7EE2;
  -moz-border-radius: 100%;
  -webkit-border-radius: 100%;
  border-radius: 100%;
  z-index: -1;
  left: -3px;
  bottom: 4px;
  margin: auto;
}
.modal-5 a.next, .modal-5 a.prev {
  color: #1E7EE2;
}
.modal-5 a.next:hover, .modal-5 a.prev:hover {
  color: #fff;
}
.modal-5 a.next:hover:after, .modal-5 a.prev:hover:after {
  display: none;
}
.modal-5 a.active {
  background: #1E7EE2;
  color: #fff;
}
.modal-5 a.active:before {
  content: ';
  position: absolute;
  top: -11px;
  left: -10px;
  awidth: 18px;
  border: 10px solid transparent;
  border-bottom: 7px solid #104477;
  z-index: -1;
}
.modal-5 a.active:hover:after {
  display: none;
}
    nav{
      background-color: white;
    }
    .one-edge-shadow {
              box-shadow: 0 8px 2px -5px rgb(246, 245, 245);
}
.display-8{
  font-weight: 200;
  font-size: 30px;
}
  </style>
</head>

<body>

  <!-- navbar -->

  <nav class="one-edge-shadow
  sticky-top navbar
  navbar-expand-lg
   navbar-light bg-white">
    <a class="navbar-brand" href="{% url 'store:homepage' %}">M-Shop</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      {% if request.session.customer_isadmin %}

      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'store:manage1' %}">Admin Product <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'store:manage1' %}">Admin Orer <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      {% else %}
      <ul class="navbar-nav mr-auto">


      </ul>
      {% endif %}



      <ul class=" navbar-nav my-2 my-lg-0">
        <li class="nav-item ">
          <a class="nav-link" href="/cart">Cart
            <span class="badge badge-info">{{request.session.cart.keys|length}}</span>
            <span class="sr-only">(current)</span></a>
        </li>
        {% if request.session.customer %}

        <li class="nav-item ">
          <a class="nav-link" href="/orders">Orders<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="/logout">Logout<span class="sr-only">(current)</span></a>
        </li>
        {% else %}

        <li class="nav-item ">
          <a class="nav-link" href="/signup">Signup<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="/login">Login<span class="sr-only">(current)</span></a>
        </li>
        {% endif %}



      </ul>


    </div>
  </nav>


    {% block content %}{% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</body>

</html>

store/templates/store/sendcodeotp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>